apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer # Maps cluster port 5000 directly to your local machine port
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend