apiVersion: v1
kind: ConfigMap
metadata:
  name: video-platform-config
data:
  MONGO_URL: "mongodb://mongodb-service:27017/videodb"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  QUEUE_NAME: "video-processing"